# Generated by Django 3.1.7 on 2021-03-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endroits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2085)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('reseaux_sociaux', models.CharField(blank=True, max_length=200)),
                ('url1', models.CharField(max_length=2085)),
                ('url2', models.CharField(max_length=2085)),
                ('url3', models.CharField(max_length=2085)),
                ('url4', models.CharField(max_length=2085)),
                ('telephone', models.IntegerField(blank=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
    ]
